stages:
  - build
  - dev_build
  - notify_failure

production_build:
  stage: build
  only:
    - master
  script:
    - npm install
    - ng build --prod
    - cd /home/gitlab-runner/builds/c30cc313/0/anonymous-coder/RotoProsWeb
    - cp -R /home/gitlab-runner/builds/c30cc313/0/anonymous-coder/RotoProsWeb/dist /var/www/html/RotoProsWeb/
  tags:
    - DFS
